/**
 * Created by golike on 2017/9/26.
 */
'use strict'

// search
export const SEARCH_HOT_WORDS = 'SEARCH_HOT_WORDS'
export const SEARCH_REFRESH_HOT_WORDS = 'SEARCH_REFRESH_HOT_WORDS'
export const SEARCH_AUTO_COMPLETE = 'SEARCH_AUTO_COMPLETE'
export const SEARCH_SEARCH_BOOKS_LOADING = 'SEARCH_SEARCH_BOOKS_LOADING'
export const SEARCH_SEARCH_BOOKS = 'SEARCH_SEARCH_BOOKS'
export const SEARCH_SEARCH_BOOKS_FAILURE = 'SEARCH_SEARCH_BOOKS_FAILURE'
export const SEARCH_BACK_TO_INIT_STATE = 'SEARCH_BACK_TO_INIT_STATE'

// bookDetailAction
export const BOOK_DETAIL = 'BOOK_DETAIL'
export const BOOK_DETAIL_LOADING = 'BOOK_DETAIL_LOADING'
export const BOOK_DETAI_FAILURE= 'BOOK_DETAI_FAILURE'
export const BOOK_HOT_REVIEW = 'BOOK_HOT_REVIEW'
export const BOOK_RECOMMEND_BOOK_LIST = 'BOOK_RECOMMEND_BOOK_LIST'

// book -- bookCommunity
export const BOOK_DISCUSSION_LIST = 'BOOK_DISCUSSION_LIST'
export const BOOK_DISCUSSION_LIST_LOADING = 'BOOK_DISCUSSION_LIST_LOADING'
export const BOOK_REVIEW_LIST = 'BOOK_REVIEW_LIST'
export const BOOK_REVIEW_LIST_LOADING = 'BOOK_REVIEW_LIST_LOADING'

// readPlatformAction
export const READ_BOOK_CHAPTER_DETAIL = 'READ_BOOK_CHAPTER_DETAIL'
export const READ_BOOK_CHAPTER_DETAIL_LOADING = 'READ_BOOK_CHAPTER_DETAIL_LOADING'
export const READ_BOOK_CHAPTER_DETAIL_FAILURE = 'READ_BOOK_CHAPTER_DETAIL_FAILURE'
export const READ_BOOK_CHAPTER_LIST = 'READ_BOOK_CHAPTER_LIST'

// discover -- charts
export const DISCOVER_CHARTS_LOADING = 'DISCOVER_CHARTS_LOADING'
export const DISCOVER_CHARTS = 'DISCOVER_CHARTS'
export const DISCOVER_CHARTS_FAILURE= 'DISCOVER_CHARTS_FAILURE'
export const DISCOVER_CHARTS_DETAIL_LOADING = 'DISCOVER_CHARTS_DETAIL_LOADING'
export const DISCOVER_CHARTS_DETAIL = 'DISCOVER_CHARTS_DETAIL'
export const DISCOVER_CHARTS_DETAIL_FAILURE= 'DISCOVER_CHARTS_DETAIL_FAILURE'

// discover -- bookList
export const DISCOVER_BOOK_LIST_LOADING = 'DISCOVER_BOOK_LIST_LOADING'
export const DISCOVER_BOOK_LIST = 'DISCOVER_BOOK_LIST'
export const DISCOVER_BOOK_LIST_FAILURE = 'DISCOVER_BOOK_LIST_FAILURE'
export const DISCOVER_BOOK_LIST_TAG = 'DISCOVER_BOOK_LIST_TAG'
export const DISCOVER_BOOK_LIST_DETAIL_LOADING = 'DISCOVER_BOOK_LIST_DETAIL_LOADING'
export const DISCOVER_BOOK_LIST_DETAIL = 'DISCOVER_BOOK_LIST_DETAIL'
export const DISCOVER_BOOK_LIST_DETAIL_FAILURE = 'DISCOVER_BOOK_LIST_DETAIL_FAILURE'
export const DISCOVER_CATEGORY_LIST_LOADING = 'DISCOVER_CATEGORY_LIST_LOADING'
export const DISCOVER_CATEGORY_LIST = 'DISCOVER_CATEGORY_LIST'
export const DISCOVER_CATEGORY_LIST_V2 = 'DISCOVER_CATEGORY_LIST_V2'
export const DISCOVER_CATEGORY_BOOKS_LOADING= 'DISCOVER_CATEGORY_BOOKS_LOADING'
export const DISCOVER_CATEGORY_BOOKS= 'DISCOVER_CATEGORY_BOOKS'
export const DISCOVER_CATEGORY_BOOKS_FAILURE= 'DISCOVER_CATEGORY_BOOKS_FAILURE'

// community -- community
export const COMMUNITY_BOOK_DISCUSSION_LIST_LOADING = 'COMMUNITY_BOOK_DISCUSSION_LIST_LOADING'
export const COMMUNITY_BOOK_DISCUSSION_LIST = 'COMMUNITY_BOOK_DISCUSSION_LIST'
export const COMMUNITY_BOOK_DISCUSSION_DETAIL_LOADING = 'COMMUNITY_BOOK_DISCUSSION_DETAIL_LOADING'
export const COMMUNITY_BOOK_DISCUSSION_DETAIL = 'COMMUNITY_BOOK_DISCUSSION_DETAIL'
export const COMMUNITY_BOOK_DISCUSSION_DETAIL_COMMENT_BEST = 'COMMUNITY_BOOK_DISCUSSION_DETAIL_COMMENT_BEST'
export const COMMUNITY_BOOK_DISCUSSION_DETAIL_COMMENT_LIST_LOADING = 'COMMUNITY_BOOK_DISCUSSION_DETAIL_COMMENT_LIST_LOADING'
export const COMMUNITY_BOOK_DISCUSSION_DETAIL_COMMENT_LIST = 'COMMUNITY_BOOK_DISCUSSION_DETAIL_COMMENT_LIST'

// community -- review
export const COMMUNITY_BOOK_REVIEW_LIST_LOADING = 'COMMUNITY_BOOK_REVIEW_LIST_LOADING'
export const COMMUNITY_BOOK_REVIEW_LIST = 'COMMUNITY_BOOK_REVIEW_LIST'
export const COMMUNITY_BOOK_REVIEW_DETAIL_LOADING = 'COMMUNITY_BOOK_REVIEW_DETAIL_LOADING'
export const COMMUNITY_BOOK_REVIEW_DETAIL = 'COMMUNITY_BOOK_REVIEW_DETAIL'
export const COMMUNITY_BOOK_REVIEW_DETAIL_COMMENT_BEST = 'COMMUNITY_BOOK_REVIEW_DETAIL_COMMENT_BEST'
export const COMMUNITY_BOOK_REVIEW_DETAIL_COMMENT_LIST_LOADING = 'COMMUNITY_BOOK_REVIEW_DETAIL_COMMENT_LIST_LOADING'
export const COMMUNITY_BOOK_REVIEW_DETAIL_COMMENT_LIST = 'COMMUNITY_BOOK_REVIEW_DETAIL_COMMENT_LIST'

// community -- review
export const COMMUNITY_BOOK_HELP_LIST_LOADING = 'COMMUNITY_BOOK_HELP_LIST_LOADING'
export const COMMUNITY_BOOK_HELP_LIST = 'COMMUNITY_BOOK_HELP_LIST'
export const COMMUNITY_BOOK_HELP_DETAIL_LOADING = 'COMMUNITY_BOOK_HELP_DETAIL_LOADING'
export const COMMUNITY_BOOK_HELP_DETAIL = 'COMMUNITY_BOOK_HELP_DETAIL'
export const COMMUNITY_BOOK_HELP_DETAIL_COMMENT_BEST = 'COMMUNITY_BOOK_HELP_DETAIL_COMMENT_BEST'
export const COMMUNITY_BOOK_HELP_DETAIL_COMMENT_LIST_LOADING = 'COMMUNITY_BOOK_HELP_DETAIL_COMMENT_LIST_LOADING'
export const COMMUNITY_BOOK_HELP_DETAIL_COMMENT_LIST = 'COMMUNITY_BOOK_HELP_DETAIL_COMMENT_LIST'

// selection -- books
export const SELECTION_NODES_LOADING = 'SELECTION_NODES_LOADING'
export const SELECTION_NODES = 'SELECTION_NODES'
export const SELECTION_NODES_FAILURE = 'SELECTION_NODES_FAILURE'
export const SELECTION_NODES_BOOKS_LOADING = 'SELECTION_NODES_BOOKS_LOADING'
export const SELECTION_NODES_BOOKS = 'SELECTION_NODES_BOOKS'
export const SELECTION_NODES_BOOKS_FAILURE = 'SELECTION_NODES_BOOKS_FAILURE'

// home -- books
export const HOME_SPREAD = 'HOME_SPREAD'